# Generated by Django 5.0.6 on 2024-06-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_activo_producto_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenProducto/'),
        ),
    ]
